//! The curated sample table, generated from the Go original's `CURATED` slice so
//! the prose is guaranteed identical. Regenerate with the extractor in
//! `devtools/` if the Go table changes.
//!
//! Ordered exactly as the playground UI presents it; `category` groups entries in
//! the dropdown. An empty `script_file` means `samples/<id>/script.capy`; an empty
//! `library_file` means `lib.capy` (with a `lib.yaml` fallback).

/// One curated entry. Field order mirrors the Go anonymous struct.
pub struct Curated {
    pub id: &'static str,
    pub category: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub hint: &'static str,
    pub script_file: &'static str,
    pub library_file: &'static str,
}

pub const CURATED: &[Curated] = &[
    Curated {
        id: "html-xml-parser",
        category: "Features",
        title: "✨ Parse HTML / XML (one function)",
        description: "A single generic `element` function parses ANY well-formed `<tag …>…</tag>` — HTML or XML. The tag name is captured, attributes match via a function-typed repetition (`attribute*`), and the block closes on the capture-bound sequence `</NAME>`. Mismatched nesting (`<div><p></div>`) is a hard parse error — real structural parsing of the tag tree.",
        hint: "Add your own nested tags or attributes; try breaking the nesting to see the mismatch error.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "bbcode-parser",
        category: "Features",
        title: "✨ BBCode tags (bracket close-seq)",
        description: "`block_close_seq` isn't angle-bracket-specific: the same primitive parses BBCode-style `[b]…[/b]` / `[quote]…[/quote]`. Each tag is its own function with a LITERAL close sequence and its own HTML template, plus a `[url=\"…\"]` attribute. Mismatched nesting is a hard parse error.",
        hint: "Swap the tag delimiters or templates; try closing `[b]` with `[/quote]` to see the error.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "markdown-from-tags",
        category: "Features",
        title: "✨ Tags → Markdown (target-agnostic)",
        description: "The SAME `<h1>…</h1>` / `<p>…</p>` / `<b>…</b>` markup that `html-xml-parser` turns into HTML is rewritten into Markdown here — only the per-tag templates differ. Shows the sequence-closer primitive is target-agnostic: it parses the tag tree; the template decides the output language.",
        hint: "Change a template (e.g. make `<b>` emit `__…__`); add an `<h2>` section.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "signature-parser",
        category: "Features",
        title: "✨ Param lists (sep + join)",
        description: "A function-signature DSL → typed declaration. The parameter list uses a function-typed repetition with BOTH separators: `param* sep \",\" join \", \"` — `sep` is the INPUT separator consumed while parsing, `join` is the OUTPUT separator inserted between rendered params. Independent, so comma-input renders as comma-space output.",
        hint: "Add a parameter to a `func` line; try a zero-arg `func now() -> int`.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "library-keywords",
        category: "Features",
        title: "✨ Authoring keywords (function/arg/block)",
        description: "The canonical `if … end` block in ~15 lines: `function` defines a source keyword, `arg literal`/`arg capture` match the line, `block_closer end` opens an indented body, and `write` + `${indent 4 body}` emit it. The building blocks every library is made of — see the Library keyword cookbook in the docs.",
        hint: "Add another statement inside the `if … end`; try nesting a second `if`.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "builtin-functions",
        category: "Features",
        title: "✨ Built-in helper functions",
        description: "A live tour of Capy's built-in template helpers — the only functions Capy itself defines. Case/identifier (`pascalCase`, `snakeCase`, `dasherize`), string/escaping (`decoded`, `escapeHtml`, `toQuoted`, `asString`), numeric (`add`, `percent`, `stars`), and layout (`indent`). See the Built-in function cookbook in the docs for all 26.",
        hint: "Change the `names`/`text`/`calc` inputs and watch each helper's output update.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "template-sugar",
        category: "Features",
        title: "✨ template … end sugar",
        description: "`template … end` replaces multi-line backtick `write` literals — same `${…}` interpolation, no backtick bookkeeping. Stacks cards from plain `card`/`p` lines.",
        hint: "Add another `card \"…\" … end` block; edit the paragraphs inside.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "optional-args",
        category: "Features",
        title: "✨ Optional args with defaults",
        description: "A trailing capture can declare a `default`, so one `button` function serves `button \"Save\"`, `button \"Delete\" \"danger\"`, and `button \"Submit\" \"primary\" \"submit\"`. Replaces whole families of near-duplicate components.",
        hint: "Drop the trailing words from a `button` line — the defaults fill in.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "line-mapping",
        category: "Features",
        title: "✨ Source↔output mapping (${line}/${col})",
        description: "Every statement exposes its source position via the `${line}` / `${col}` render locals. The library stamps them as `data-capy-line` so an editor can scroll-sync or place inline errors — no source mutation.",
        hint: "Add or remove a `p` line; watch the `data-capy-line` numbers track the source.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "string-decoded",
        category: "Features",
        title: "✨ decoded — escapes & quotes round-trip",
        description: "`${decoded}` resolves `\\n` / `\\t` and embedded `\\\"` quotes in captured prose, even when the text itself contains quotes. `${escapeHtml}` then neutralises markup.",
        hint: "Add a `p` with your own quotes, newlines (`\\n`) and `<tags>`.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "verbatim-pre",
        category: "Features",
        title: "✨ block_verbatim — raw code blocks",
        description: "`pre LANG … end` captures its body as raw bytes (no re-parsing), HTML-escapes it, and emits `<pre><code>`. Blank lines and `#`-prefixed lines survive byte-for-byte.",
        hint: "Paste a snippet in any language inside a `pre … end` block.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "backtick-codespan",
        category: "Features",
        title: "✨ Escapable backticks in captures",
        description: "A backtick-delimited capture can contain a Markdown code span: `\\`code\\`` stays literal instead of closing the capture.",
        hint: "Add a `markdown` line with your own `\\`inline code\\``.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "utf8-prose",
        category: "Features",
        title: "✨ UTF-8 prose (no quoting)",
        description: "Em-dashes, accented Latin, CJK and emoji tokenise as ordinary idents — bare prose Just Works without wrapping in quotes.",
        hint: "Type a sentence in any language; it becomes a paragraph.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "multiline-strings",
        category: "Features",
        title: "✨ Multi-line backtick captures",
        description: "Backtick string captures span newlines in user scripts, so a paragraph can wrap across several source lines — blank lines preserved.",
        hint: "Edit a `p \\`…\\`` block to span more lines.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "inline-markdown",
        category: "Features",
        title: "✨ Group types — inline syntax",
        description: "Group types (`group_open`/`group_close`) let captures consume delimited spans: `link [text](url)`, `bold **text**`, `strike ~~text~~` map cleanly onto HTML.",
        hint: "Add a `link [label](https://…)` or `bold **word**` line.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "feature-faq",
        category: "Features",
        title: "✨ FAQ (template + optional flag)",
        description: "An FAQ DSL: `q \"…\" open` toggles `<details open>` via an optional arg (default \"closed\"); answers are decoded + escaped.",
        hint: "Drop or add the `open` flag on a `q` line; edit the answers.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "feature-pricing",
        category: "Features",
        title: "✨ Pricing tiers (optional period/CTA)",
        description: "`tier \"Pro\" \"$29\"` works; add `\"/yr\" \"Contact sales\"` to override the period and button. One function, no duplicate variants.",
        hint: "Add a `feature` line or a fourth `tier`.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "feature-callouts",
        category: "Features",
        title: "✨ Callouts (note/tip/warning)",
        description: "Admonition blocks where the style is an optional trailing word (default \"note\"). Body markup is escaped so `<script>` is inert.",
        hint: "Change `tip`/`warning`, or omit it for the default note style.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "feature-svg-badge",
        category: "Features",
        title: "✨ SVG badges (verbatim body)",
        description: "`badge \"label\" … end` captures raw inline SVG byte-for-byte — angle brackets, attributes and line breaks untouched, zero escaping.",
        hint: "Edit the SVG colours or text inside a `badge … end` block.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "feature-menu-i18n",
        category: "Features",
        title: "✨ Multilingual menu (UTF-8 + tail)",
        description: "A restaurant menu in French, Japanese & Chinese. `dish` keeps the name as a string and slurps the free-text description with a `tail` capture.",
        hint: "Add a `dish \"Name\" \"price\" your description here` line.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "feature-changelog",
        category: "Features",
        title: "✨ Changelog (line + verbatim + optional)",
        description: "Release notes mixing `${line}` mapping, optional `kind` (added/fixed/removed), and a verbatim `upgrade` code block.",
        hint: "Add a `change \"…\" added` line or a new `release … end`.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "feature-social-card",
        category: "Features",
        title: "✨ Social preview cards",
        description: "Open-Graph-style cards via `template … end`, with an optional `theme` arg (default \"light\") and safe escaping of arbitrary punctuation.",
        hint: "Add `dark` after a card title, or a new `tag`.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "feature-stepper",
        category: "Features",
        title: "✨ Onboarding stepper (${line})",
        description: "A how-to stepper; each `step` stamps its source line for scroll-sync, with an optional `done` status flag.",
        hint: "Reorder steps or toggle the `done` flag.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "feature-glossary",
        category: "Features",
        title: "✨ Glossary (multi-line + code spans)",
        description: "Definition list where each term's body is a multi-line backtick capture containing `\\`code\\`` spans that round-trip.",
        hint: "Add a `term \"Name\" \\`multi-line body\\`` entry.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "feature-quiz",
        category: "Features",
        title: "✨ Quiz (optional correct flag)",
        description: "Multiple-choice quiz: `choice \"…\" correct` marks the answer via an optional flag (default \"wrong\"); questions stamp their source line.",
        hint: "Add a `choice` or a whole new `question … end`.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "mcp-widgets",
        category: "Features",
        title: "✨ MCP widgets (everything at once)",
        description: "Weather / chart / product-card widgets that exercise nested blocks, templates, decoded + escapeHtml, and context accumulation together.",
        hint: "Edit the forecast days, bar values, or product details.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "math-plots",
        category: "Features",
        title: "✨ Math plots (template + canvas)",
        description: "`plot \"EXPR\" … end` → a self-contained `<canvas>` + `drawPlot()` call. Uses `template … end`, `${decoded}`, `${escapeHtml}` and context accumulation.",
        hint: "Change an expression, domain, color, or sample count.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "word-frequency",
        category: "Indexed reads",
        title: "🔢 Word frequency (map increment)",
        description: "`see word` does `set context.counts[w] (add context.counts[w] 1)` — a map element read, incremented, and written back (nil counts as 0). `bar word` then reads `${context.counts[w]}` to draw a star bar. The whole counter is one indexed read/write idiom.",
        hint: "Add more `see <word>` lines; the bars grow.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "memo-fib",
        category: "Indexed reads",
        title: "🔢 Memoised Fibonacci (computed index)",
        description: "`memo [ 0 1 ]` seeds a list; `fib n` appends and reads back two earlier cells with computed indices `${context.memo[(sub n 1)]}` + `${context.memo[(sub n 2)]}`. Arithmetic inside the `[…]` resolves at read time.",
        hint: "Ask for more `fib` values; each reuses the memo table.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "stack-top",
        category: "Indexed reads",
        title: "🔢 Stack peek (negative index)",
        description: "`push v` appends; `top` reads `${context.stack[-1]}` and `${context.stack[-2]}` — negative indices count from the end, matching write-side semantics.",
        hint: "Push or pop values and re-peek the top.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "enum-lookup",
        category: "Indexed reads",
        title: "🔢 Enum lookup (list by index)",
        description: "`days`/`months` are fixed lists; `event d m …` reads `${context.days[d]}` / `${context.months[m]}` to resolve a weekday and month name by numeric index — a classic lookup table.",
        hint: "Change the day/month numbers or add an `event` line.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "leaderboard",
        category: "Indexed reads",
        title: "🔢 Leaderboard (positional reads)",
        description: "`rank name` builds a list; `podium` reads fixed positions `[0]`/`[1]`/`[2]` for gold/silver/bronze and `[-1]` for last place.",
        hint: "Add or reorder `rank` lines; the podium tracks positions.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "color-palette",
        category: "Indexed reads",
        title: "🔢 Color palette (map by name)",
        description: "`def name color` records `context.palette[name]`; `swatch name` reads `${context.palette[name]}` by key to emit a colored chip. One `swatch` function serves any color the palette defines.",
        hint: "Add a `def <name> <css-color>` then a matching `swatch`.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "recipe-card",
        category: "Everyday",
        title: "🍋 Recipe card",
        description: "Write a recipe in plain words; get a printable HTML recipe card.",
        hint: "Try editing the title, ingredients, or steps.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "event-invite",
        category: "Everyday",
        title: "🎉 Party invitation",
        description: "Declare a party; get a pastel HTML invitation card.",
        hint: "Try changing the host, location, or RSVP date.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "weekly-meal-plan",
        category: "Everyday",
        title: "📅 Weekly meal plan",
        description: "Seven dinners + notes → printable HTML grid for the fridge.",
        hint: "Swap meals or add notes.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "reading-log",
        category: "Everyday",
        title: "📚 Reading log (for kids)",
        description: "A kid's reading list → bright HTML certificate with progress bar.",
        hint: "Add more `book` lines; the progress bar updates.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "trip-itinerary",
        category: "Everyday",
        title: "✈️ Trip itinerary",
        description: "Day-by-day travel plan → polished HTML itinerary card.",
        hint: "Edit destinations, add activities, change the budget.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-resume",
        category: "Everyday",
        title: "📄 Resume",
        description: "A resume DSL → a clean printable resume.",
        hint: "Edit experience and skills lines.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-invoice",
        category: "Everyday",
        title: "🧾 Invoice",
        description: "Declare an invoice; get a polished HTML invoice you can print.",
        hint: "Edit the line items and rates.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-markdown-todo",
        category: "Everyday",
        title: "✅ To-do list",
        description: "A tiny todo DSL → Markdown checklist.",
        hint: "Add tasks, mark them done.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "interactive-breakout",
        category: "Games",
        title: "🕹️ Breakout (playable)",
        description: "Event-driven Breakout: entities + key bindings + event handlers → 226-line HTML5 game.",
        hint: "Change `lives 3` to `lives 5`, or rebind keys.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "interactive-snake",
        category: "Games",
        title: "🐍 Snake (playable)",
        description: "Event-driven Snake: key bindings + event handlers → 180-line HTML5 game.",
        hint: "Try changing `tick every 110` to a smaller number for faster gameplay.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-canvas-game",
        category: "Games",
        title: "🎮 Canvas game",
        description: "A tiny game DSL → full HTML5 canvas game with sprites + input handlers.",
        hint: "Add new sprites or key bindings.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "scene-dsl",
        category: "Games",
        title: "🎬 Scene description",
        description: "High-level scene declaration → rendering-engine setup.",
        hint: "Add new entities.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-threejs",
        category: "3D",
        title: "🌐 Three.js scene (interactive)",
        description: "~25 declarative lines → a runnable, interactive three.js page. Declare meshes, abstract motions (spin/orbit/bob/pulse), and EVENT bindings — `click <target> <action>`, `hover`, `key`, `button` — wired to named actions (randomize_color, toggle_motion, cycle_motion, wireframe, explode, disco, reset_all). Raycaster picks objects, keys dispatch actions, HUD buttons fire actions. Drag to orbit, scroll to zoom.",
        hint: "Click any object; press Space, R, D, X, W; or hit the HUD buttons. Try adding `click ring explode` or `key \"q\" any disco`.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-landing-page",
        category: "Web",
        title: "🌐 Landing page",
        description: "Marketing landing page DSL → polished HTML.",
        hint: "Change the headline, hero text, CTAs.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-react-component",
        category: "Web",
        title: "⚛️ React component",
        description: "Component declaration → React TSX with props + state.",
        hint: "Add new props or component fields.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "html-component",
        category: "Web",
        title: "✨ HTML component",
        description: "Card / badge / hero primitives → ready-to-paste HTML+CSS.",
        hint: "Try different variants.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-css-animations",
        category: "Web",
        title: "🎨 CSS animations",
        description: "Animation DSL → @keyframes + utility classes.",
        hint: "Tweak duration or easing.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-email-html",
        category: "Web",
        title: "📧 Email HTML",
        description: "Email template DSL → inline-styled HTML for email clients.",
        hint: "Edit headline, body, CTA.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-form",
        category: "Web",
        title: "📝 HTML form",
        description: "Form field declarations → a styled HTML form.",
        hint: "Add or remove fields.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-blog",
        category: "Web",
        title: "📰 Blog post",
        description: "Blog-post DSL → Markdown with frontmatter + structured content.",
        hint: "Add new sections.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "supercharge-markdown",
        category: "Web",
        title: "📝 Markdown w/ callouts",
        description: "Markdown extension DSL → real Markdown with HTML callouts + metric cards.",
        hint: "Add more `callout` or `card` blocks.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-mermaid",
        category: "Diagrams",
        title: "🌊 Mermaid diagram",
        description: "High-level flow DSL → Mermaid syntax.",
        hint: "Add new nodes or edges.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-csv",
        category: "Diagrams",
        title: "📊 CSV",
        description: "Tabular DSL → CSV with header row.",
        hint: "Add columns or rows.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-json",
        category: "Diagrams",
        title: "🗂️ JSON",
        description: "Structured DSL → indented JSON output.",
        hint: "Add nested fields.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-dockerfile",
        category: "DevOps",
        title: "🐳 Dockerfile",
        description: "Multi-stage Docker build DSL → real Dockerfile.",
        hint: "Add layers or environment variables.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-kubernetes",
        category: "DevOps",
        title: "☸️ Kubernetes manifest",
        description: "Deployment + service DSL → full K8s YAML.",
        hint: "Add containers, change replicas.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-terraform",
        category: "DevOps",
        title: "🏗️ Terraform module",
        description: "Infrastructure DSL → Terraform HCL.",
        hint: "Add resources or variables.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-makefile",
        category: "DevOps",
        title: "⚙️ Makefile",
        description: "Build-target DSL → real Makefile.",
        hint: "Add new targets and dependencies.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-nginx",
        category: "DevOps",
        title: "🌐 nginx config",
        description: "Server block DSL → nginx configuration.",
        hint: "Add upstreams or rewrite rules.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-gh-actions",
        category: "DevOps",
        title: "⚡ GitHub Actions",
        description: "Workflow DSL → GitHub Actions YAML.",
        hint: "Add new jobs or steps.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-cron",
        category: "DevOps",
        title: "⏰ Cron",
        description: "Schedule + command DSL → crontab lines.",
        hint: "Add scheduled tasks.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-prometheus-alerts",
        category: "DevOps",
        title: "🚨 Prometheus alerts",
        description: "Alert-rule DSL → Prometheus alerting rules YAML.",
        hint: "Add new alerts.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-env",
        category: "DevOps",
        title: "🔐 .env file",
        description: "Env-var DSL → dotenv config.",
        hint: "Add new variables.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-systemd",
        category: "DevOps",
        title: "🐧 systemd unit",
        description: "Service DSL → systemd .service unit file.",
        hint: "Edit ExecStart and dependencies.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-chrome-extension",
        category: "DevOps",
        title: "🌐 Chrome extension manifest",
        description: "Extension config DSL → manifest.json v3.",
        hint: "Add permissions or content scripts.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "supercharge-sql",
        category: "DevOps",
        title: "💎 SQL DDL with macros",
        description: "Macros (pk/fk/timestamps/soft_delete) → idiomatic Postgres DDL.",
        hint: "Add new tables.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-postgres-schema",
        category: "Schemas",
        title: "🗃️ Postgres schema",
        description: "Table DSL → CREATE TABLE + indexes + foreign keys.",
        hint: "Add tables and references.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-prisma-schema",
        category: "Schemas",
        title: "💠 Prisma schema",
        description: "Model DSL → Prisma schema.prisma.",
        hint: "Add models or relations.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-openapi",
        category: "Schemas",
        title: "🔭 OpenAPI spec",
        description: "Endpoint DSL → OpenAPI 3.0 YAML.",
        hint: "Add endpoints, parameters, responses.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-graphql",
        category: "Schemas",
        title: "📡 GraphQL schema",
        description: "Type DSL → GraphQL SDL.",
        hint: "Add types and resolvers.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-zod-schema",
        category: "Schemas",
        title: "🛡️ Zod schema",
        description: "Type DSL → Zod TypeScript validation schemas.",
        hint: "Add fields or refinements.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-typescript",
        category: "Schemas",
        title: "📑 TypeScript types",
        description: "Struct DSL → TypeScript interfaces + types.",
        hint: "Add fields.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-protobuf",
        category: "Schemas",
        title: "📐 Protobuf",
        description: "Message DSL → .proto definitions.",
        hint: "Add messages and services.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-api-docs",
        category: "Schemas",
        title: "📋 API docs",
        description: "Endpoint DSL → Markdown API reference.",
        hint: "Add new endpoints.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "typed-config-dsl",
        category: "Schemas",
        title: "🔒 Typed config (HCL)",
        description: "Service config DSL with custom types (Email, Semver, LogLevel) → HCL.",
        hint: "Add new services. Bad values give clear type errors.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "metaprogramming",
        category: "Schemas",
        title: "🧬 Metaprogramming",
        description: "Source declares its own DSL primitives via `define ... end` — the library doesn't need them.",
        hint: "Add a new `define ...` block at the top and use it below — your source extends the grammar.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "host-capabilities",
        category: "Schemas",
        title: "🔌 Host capabilities (env / args / read_file)",
        description: "Generates a Kubernetes deployment from env vars, CLI args, and a sibling secrets file. The CLI's OSHost exposes real values; the playground's sandboxed NoOpHost returns empty strings (read the description in the output for context).",
        hint: "In the CLI: ENV=production capy run lib.capy script.capy v2.3.1 us-west-2. In the playground: see how the same library degrades cleanly when env/args are empty.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "cross-platform-installer",
        category: "DevOps",
        title: "📦 Cross-platform installer (sh/ps1/bat)",
        description: "One DSL declares `install foo`, `mkdir bar`, `setenv X Y`, `service svc`. Multi-file output emits a bash installer, a PowerShell installer, AND a CMD installer — all in lock-step.",
        hint: "Add another `install` line; all three scripts get it.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-websocket-server",
        category: "Code",
        title: "🔌 WebSocket server (Go)",
        description: "9 declarative lines → a complete Go WebSocket chat server (~80 lines) with typed JSON envelope, message dispatch, hub, and broadcast helper.",
        hint: "Add another `message` + `on` pair; the dispatch grows automatically.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "multi-target-ws-server",
        category: "Code",
        title: "🌐 WS server · Go",
        description: "Same 7-line ws DSL → Go (gorilla/websocket). Switch the library to retarget Node or Python.",
        hint: "Compare with the Node and Python variants in the dropdown.",
        script_file: "",
        library_file: "lib-go.capy",
    },
    Curated {
        id: "multi-target-ws-server",
        category: "Code",
        title: "🌐 WS server · Node",
        description: "Same 7-line ws DSL → Node.js (ws package).",
        hint: "Compare with the Go and Python variants. The source is identical.",
        script_file: "",
        library_file: "lib-node.capy",
    },
    Curated {
        id: "multi-target-ws-server",
        category: "Code",
        title: "🌐 WS server · Python",
        description: "Same 7-line ws DSL → Python (websockets + asyncio).",
        hint: "Compare with the Go and Node variants. The source is identical.",
        script_file: "",
        library_file: "lib-python.capy",
    },
    Curated {
        id: "custom-asm",
        category: "Code",
        title: "⚙️ Assembly · x86_64",
        description: "Architecture-neutral assembly DSL (data / func / write / exit) → GNU as syntax for x86_64 Linux (System V). 5-line source → runnable hello-world.",
        hint: "Switch to the arm64 or riscv64 variant; identical source, different syscall ABI.",
        script_file: "",
        library_file: "lib-x86_64-linux.capy",
    },
    Curated {
        id: "custom-asm",
        category: "Code",
        title: "⚙️ Assembly · arm64",
        description: "Same source → AArch64 (ARM64) Linux assembly. Syscall number in x8, args in x0-x5, svc #0.",
        hint: "Compare with the x86_64 and riscv64 variants.",
        script_file: "",
        library_file: "lib-arm64-linux.capy",
    },
    Curated {
        id: "custom-asm",
        category: "Code",
        title: "⚙️ Assembly · riscv64",
        description: "Same source → RISC-V 64 (RV64I) Linux assembly. Syscall number in a7, args in a0-a5, ecall.",
        hint: "Compare with the x86_64 and arm64 variants. Add new architectures by writing a new library.",
        script_file: "",
        library_file: "lib-riscv64-linux.capy",
    },
    Curated {
        id: "progressive-abstraction",
        category: "Patterns",
        title: "🎚️ Abstraction · Level 1 (one-shot)",
        description: "4-line `landing` declaration. The library decides everything else.",
        hint: "Tweak the tagline or CTA. Want more control? Try Level 2.",
        script_file: "script_minimal.capy",
        library_file: "",
    },
    Curated {
        id: "progressive-abstraction",
        category: "Patterns",
        title: "🎚️ Abstraction · Level 2 (blocks)",
        description: "~12-line block style. You pick which sections appear and in what order; library owns visuals.",
        hint: "Add another `feature` line. Want full control? Try Level 3.",
        script_file: "script_medium.capy",
        library_file: "",
    },
    Curated {
        id: "progressive-abstraction",
        category: "Patterns",
        title: "🎚️ Abstraction · Level 3 (escape hatches)",
        description: "~30 lines. Same primitives PLUS raw_head / style_override / raw_section / raw_footer.",
        hint: "Anything you'd write in raw HTML/CSS, drop in here. The library never blocks you.",
        script_file: "script_full.capy",
        library_file: "",
    },
    Curated {
        id: "transpile-py",
        category: "Code",
        title: "🐍 Python script",
        description: "Source language DSL → Python.",
        hint: "Try adding more functions.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-express-server",
        category: "Code",
        title: "🚂 Express server",
        description: "Route DSL → Express.js handlers.",
        hint: "Add new endpoints.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-flask-app",
        category: "Code",
        title: "🌶️ Flask app",
        description: "Route DSL → Python Flask handlers.",
        hint: "Add new routes.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-fastapi-app",
        category: "Code",
        title: "⚡ FastAPI app",
        description: "Route DSL → Python FastAPI handlers.",
        hint: "Add new endpoints with type hints.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-go",
        category: "Code",
        title: "🐹 Go",
        description: "Source language DSL → idiomatic Go.",
        hint: "Add functions or types.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-cli",
        category: "Code",
        title: "💼 CLI app",
        description: "Flag DSL → CLI argument parsing scaffold.",
        hint: "Add new flags.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-slack-blocks",
        category: "Code",
        title: "💬 Slack message",
        description: "Block-kit DSL → Slack message JSON.",
        hint: "Try different block types.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-statemachine",
        category: "Code",
        title: "🔄 State machine",
        description: "State + transition DSL → runnable state-machine code.",
        hint: "Add states or transitions.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-xstate-machine",
        category: "Code",
        title: "🎛️ XState machine",
        description: "State-chart DSL → XState v5 machine config.",
        hint: "Add states or guards.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-bash",
        category: "Code",
        title: "🐚 Bash script",
        description: "Command DSL → portable bash script.",
        hint: "Add new commands.",
        script_file: "",
        library_file: "",
    },
    Curated {
        id: "transpile-changelog",
        category: "Code",
        title: "📋 Changelog",
        description: "Release entry DSL → Keep-a-Changelog Markdown.",
        hint: "Add new releases.",
        script_file: "",
        library_file: "",
    },
];
