//! Embed Capy in a Rust program to define a tiny HTML DSL inline.
//!
//! Run: `cargo run --manifest-path examples/embed-html-dsl/Cargo.toml`
//!
//! This binary ships its own grammar — there is no `lib.capy` file on disk. The
//! library is a string constant compiled into the program.

use capy_core::capy::Library;

// A raw string with a `#` fence: the library body contains backticks and quotes,
// and `${…}` is Capy's interpolation syntax, not Rust's.
const HTML_LIB: &str = r#"
extension html

function page
    arg literal "page"
    arg capture title string
    block_closer end
    write `<!DOCTYPE html>
<html>
  <head><title>${title}</title></head>
  <body>
${indent 4 body}
  </body>
</html>
`
end

function h1
    arg literal "h1"
    arg capture text string
    write `<h1>${text}</h1>
`
end

function p
    arg literal "p"
    arg capture text string
    write `<p>${text}</p>
`
end

function link
    arg literal "link"
    arg capture text string
    arg capture href string
    write `<a href=${href}>${text}</a>
`
end

function end
end
"#;

const SOURCE: &str = r#"
page "Hello from embedded Capy"
    h1 "Welcome!"
    p  "This entire page was generated by a Capy library compiled INTO this Rust binary."
    p  "No external lib.capy, no separate capy CLI."
    link "Source" "https://github.com/olivierdevelops/capy"
end
"#;

fn main() {
    let lib = match Library::new(HTML_LIB) {
        Ok(l) => l,
        Err(e) => {
            eprintln!("compile library: {e}");
            std::process::exit(1);
        }
    };
    match lib.run(SOURCE) {
        Ok(out) => print!("{out}"),
        Err(e) => {
            eprintln!("run: {e}");
            std::process::exit(1);
        }
    }
}
