//! `capy build` — produces a standalone executable with a library baked in. Run
//! it against any script and it dispatches to the library's commands; no `capy`
//! install is needed on the target host.
//!
//! Implementation: writes a temporary Cargo project whose `main.rs` embeds the
//! library source and calls `capy_core::orchestrator::commands::run_command`,
//! then shells out to `cargo build --release`.
//!
//!   * running `capy build` needs a Cargo toolchain
//!   * the OUTPUT binary embeds the Rust engine and needs no toolchain
//!   * `--target <triple>` cross-compiles; it replaces the Go build's
//!     GOOS/GOARCH, so `--target wasm32-unknown-unknown` yields a `.wasm`
//!
//! This replaces the Go original, which generated a Go module importing
//! `github.com/olivierdevelops/capy/orchestrator`. The observable contract — the
//! produced binary's CLI, its `--help`, and the commands it dispatches — is
//! unchanged; only the engine inside it is.

use super::flags::{self, reorder_flags_first, Spec};
use super::lib_path::resolve_lib;
use capy_core::gopath;
use std::process::Command;

const BUILD_SPEC: Spec = Spec { bools: &["keep-temp"], strings: &["o", "target"] };

/// Port of `cmdBuild`.
pub fn cmd_build(args: &[String]) -> Result<(), String> {
    // Go's flag package stops at the first positional, so flags move to the front.
    let args = reorder_flags_first(args);
    let fs = flags::parse(&BUILD_SPEC, &args)?;
    let pos = &fs.positionals;
    if pos.len() != 1 {
        return Err(
            "usage: capy build <library> [-o <output>] [--target <triple>]".to_string(),
        );
    }
    let lib_name = &pos[0];

    // Resolve the library — by name on CAPY_LIBS, or by direct path.
    let lib_path = match resolve_lib(lib_name) {
        Ok(p) => p,
        Err(_) => {
            if std::fs::metadata(lib_name).is_ok() {
                lib_name.clone()
            } else {
                return Err(format!("library {:?} not found", lib_name));
            }
        }
    };

    let lib_src = std::fs::read_to_string(&lib_path)
        .map_err(|e| format!("read library: {}", gopath::io_error("open", &lib_path, &e)))?;

    // Default output path.
    let base = gopath::base(&lib_path);
    let ext = gopath::ext(&lib_path);
    let resolved_name = base.strip_suffix(&ext).unwrap_or(&base).to_string();
    let mut out = fs.str("o").to_string();
    if out.is_empty() {
        out = format!("./{}", resolved_name);
    }

    // Materialise a temp Cargo project with the library source embedded.
    let tmp_dir = make_temp_dir("capy-build-")?;
    let keep = fs.bool("keep-temp");
    let cleanup = |dir: &str, keep: bool| {
        if !keep {
            let _ = std::fs::remove_dir_all(dir);
        }
    };

    let src_dir = gopath::join(&[&tmp_dir, "src"]);
    std::fs::create_dir_all(&src_dir)
        .map_err(|e| gopath::io_error("mkdir", &src_dir, &e))?;
    let main_rs_path = gopath::join(&[&src_dir, "main.rs"]);
    std::fs::write(&main_rs_path, build_main_rs(&resolved_name, &lib_src).as_bytes())
        .map_err(|e| format!("write main.rs: {}", gopath::io_error("open", &main_rs_path, &e)))?;

    // Prefer a local checkout so an offline build works and the binary matches
    // the engine that produced it — the equivalent of the Go version's
    // `replace` directive. Fall back to the published crate.
    let dep = match find_capy_core_root() {
        Some(root) => format!("capy-core = {{ path = {} }}", toml_string(&root)),
        None => format!("capy-core = {}", toml_string(CAPY_CORE_VERSION)),
    };
    let cargo_toml = format!(
        "# Generated by capy build. Do not edit.\n\
         [package]\n\
         name = \"capybuild\"\n\
         version = \"0.0.0\"\n\
         edition = \"2021\"\n\
         \n\
         [[bin]]\n\
         name = \"capybuild\"\n\
         path = \"src/main.rs\"\n\
         \n\
         [dependencies]\n\
         {dep}\n\
         \n\
         # Match the engine's own release profile: a bundled tool wants to be small.\n\
         [profile.release]\n\
         opt-level = \"z\"\n\
         lto = true\n\
         codegen-units = 1\n\
         strip = true\n"
    );
    let cargo_toml_path = gopath::join(&[&tmp_dir, "Cargo.toml"]);
    if let Err(e) = std::fs::write(&cargo_toml_path, cargo_toml.as_bytes()) {
        cleanup(&tmp_dir, keep);
        return Err(format!(
            "write Cargo.toml: {}",
            gopath::io_error("open", &cargo_toml_path, &e)
        ));
    }

    let abs_out = if gopath::is_abs(&out) {
        gopath::clean(&out)
    } else {
        let cwd = std::env::current_dir()
            .map(|p| p.to_string_lossy().into_owned())
            .unwrap_or_default();
        gopath::join(&[&cwd, &out])
    };

    eprintln!("building {} (this needs the Cargo toolchain)…", resolved_name);
    // --target-dir inside the temp dir keeps the build self-contained, so it
    // neither pollutes nor is polluted by a surrounding workspace.
    let target_dir = gopath::join(&[&tmp_dir, "target"]);
    // `--target <triple>` cross-compiles, replacing the Go build's GOOS/GOARCH
    // env vars — notably `--target wasm32-unknown-unknown` for a browser build.
    let triple = fs.str("target").to_string();
    if triple.starts_with("wasm32") {
        // Be explicit rather than shipping a module that fails at run time. The
        // generated wrapper stages the embedded library through a temp file, and
        // wasm32-unknown-unknown has no filesystem at all while WASI needs the
        // host to grant one — so `--help` works but commands panic without it.
        // A browser-ready build is a different artefact: see capy-wasm-abi.
        eprintln!(
            "warning: a wasm target needs a host-provided filesystem for the staged\n\
             library file; `--help` works but commands will fail without one.\n\
             For the browser, build the capy-wasm-abi crate instead — it exposes\n\
             capy_run/capy_docs/capy_introspect over linear memory, with no files."
        );
    }
    let mut cargo_args: Vec<&str> = vec!["build", "--release", "--target-dir", &target_dir];
    if !triple.is_empty() {
        cargo_args.push("--target");
        cargo_args.push(&triple);
    }
    let build = Command::new("cargo")
        .args(&cargo_args)
        .current_dir(&tmp_dir)
        .status();
    match build {
        Ok(st) if st.success() => {}
        Ok(st) => {
            cleanup(&tmp_dir, keep);
            return Err(format!("cargo build failed: exit status {}", st.code().unwrap_or(-1)));
        }
        Err(e) => {
            cleanup(&tmp_dir, keep);
            return Err(format!("cargo build failed: {}", e));
        }
    }

    // Cargo names the artefact after the bin target rather than honouring an
    // output path, so move it into place ourselves. A cross-compile also nests
    // the artefact one level deeper, under the triple.
    let exe = if triple.starts_with("wasm32") {
        "capybuild.wasm".to_string()
    } else if triple.contains("windows") || (triple.is_empty() && cfg!(windows)) {
        "capybuild.exe".to_string()
    } else {
        "capybuild".to_string()
    };
    let produced = if triple.is_empty() {
        gopath::join(&[&target_dir, "release", &exe])
    } else {
        gopath::join(&[&target_dir, &triple, "release", &exe])
    };
    if let Err(e) = std::fs::copy(&produced, &abs_out) {
        cleanup(&tmp_dir, keep);
        return Err(format!("install binary: {}", gopath::io_error("open", &produced, &e)));
    }
    #[cfg(unix)]
    if !triple.starts_with("wasm32") {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&abs_out, std::fs::Permissions::from_mode(0o755));
    }

    let size = std::fs::metadata(&abs_out).map(|m| m.len()).unwrap_or(0);
    eprintln!("✓ wrote {} ({:.1} MB)", out, size as f64 / 1024.0 / 1024.0);
    eprintln!("  try:  {} --help", out);
    cleanup(&tmp_dir, keep);
    Ok(())
}

/// The published `capy-core` version the generated project depends on when no
/// local checkout is found. Kept in step with the workspace version.
const CAPY_CORE_VERSION: &str = env!("CARGO_PKG_VERSION");

/// The source of the standalone wrapper binary. Embeds the library source as a
/// constant and dispatches every invocation to `run_command`, mirroring what the
/// Go template did with `orchestrator.RunCommand`.
fn build_main_rs(lib_name: &str, lib_src: &str) -> String {
    format!(
        r###"// Generated by capy build. Do not edit.
use std::io::Write;

const LIB_NAME: &str = {name};

const LIB_SOURCE: &str = {src};

fn main() {{
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.is_empty() || args[0] == "--help" || args[0] == "-h" {{
        print_usage();
        return;
    }}
    // The library is EMBEDDED in this binary; the user already trusted it by
    // running the binary. Suppress the "not on CAPY_LIBS" warning that would
    // otherwise fire for the temp-file path.
    std::env::set_var("CAPY_TRUST", "1");

    let path = std::env::temp_dir().join(format!("capy-lib-{{}}.capy", std::process::id()));
    match std::fs::File::create(&path).and_then(|mut f| f.write_all(LIB_SOURCE.as_bytes())) {{
        Ok(()) => {{}}
        Err(e) => {{
            eprintln!("{{e}}");
            std::process::exit(1);
        }}
    }}
    let result = capy_core::orchestrator::commands::run_command(
        &path.to_string_lossy(),
        &args[0],
        &args[1..],
    );
    let _ = std::fs::remove_file(&path);
    if let Err(e) = result {{
        eprintln!("{{}}", e.msg);
        std::process::exit(1);
    }}
}}

fn print_usage() {{
    println!("{{LIB_NAME}} \u{{2014}} bundled Capy library (built with capy build)\n");
    println!("USAGE");
    println!("    {{LIB_NAME}} <command> [args...]\n");
    println!("Try --help for command-specific help.");
}}
"###,
        name = rust_string_literal(lib_name),
        src = rust_raw_string_literal(lib_src)
    )
}

/// Encodes `s` as a Rust raw-string literal, widening the `#` fence until it
/// cannot collide with the content. A `.capy` library routinely contains `"#`
/// (`line "#"`, shell comments in a template), which would otherwise terminate
/// the literal early and produce source that doesn't compile.
fn rust_raw_string_literal(s: &str) -> String {
    let mut hashes = 1;
    while s.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let fence = "#".repeat(hashes);
    format!("r{fence}\"{s}\"{fence}")
}

/// Encodes `s` as an ordinary escaped Rust string literal.
fn rust_string_literal(s: &str) -> String {
    let mut b = String::from("\"");
    for c in s.chars() {
        match c {
            '\\' => b.push_str("\\\\"),
            '"' => b.push_str("\\\""),
            '\n' => b.push_str("\\n"),
            '\t' => b.push_str("\\t"),
            '\r' => b.push_str("\\r"),
            other => b.push(other),
        }
    }
    b.push('"');
    b
}

/// Encodes `s` as a TOML basic string, for embedding a filesystem path in the
/// generated `Cargo.toml` (Windows paths contain backslashes).
fn toml_string(s: &str) -> String {
    rust_string_literal(s)
}

/// Looks up from the cwd (and from this binary's location) for the `Cargo.toml`
/// that declares `name = "capy-core"` — the analogue of the Go version's
/// `findCapyModuleRoot`.
fn find_capy_core_root() -> Option<String> {
    let mut candidates: Vec<String> = Vec::new();
    if let Ok(cwd) = std::env::current_dir() {
        candidates.push(cwd.to_string_lossy().into_owned());
    }
    if let Ok(self_exe) = std::env::current_exe() {
        candidates.push(gopath::dir(&self_exe.to_string_lossy()));
    }
    for start in candidates {
        let mut dir = start;
        for _ in 0..12 {
            // The engine may sit in the directory itself, or in a `rust/`
            // subdirectory of a repo checkout.
            for cand in [dir.clone(), gopath::join(&[&dir, "rust"])] {
                let manifest = gopath::join(&[&cand, "Cargo.toml"]);
                if let Ok(data) = std::fs::read_to_string(&manifest) {
                    if data.contains("name = \"capy-core\"") {
                        return Some(cand);
                    }
                }
            }
            let parent = gopath::dir(&dir);
            if parent == dir {
                break;
            }
            dir = parent;
        }
    }
    None
}

/// Stand-in for `os.MkdirTemp`.
fn make_temp_dir(prefix: &str) -> Result<String, String> {
    let base = std::env::temp_dir();
    for _ in 0..1000 {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let p = base.join(format!("{}{}{}", prefix, std::process::id(), nanos));
        match std::fs::create_dir(&p) {
            Ok(_) => return Ok(p.to_string_lossy().into_owned()),
            Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(e) => return Err(gopath::io_error("mkdir", &p.to_string_lossy(), &e)),
        }
    }
    Err("mkdirtemp: exhausted attempts".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The fence has to widen past any `"#` sequence in the library source, or the
    /// generated main.rs won't compile. `.capy` libraries hit this in practice —
    /// `line "#"` for a shell comment is ordinary — and it bit this port three
    /// times while it was being written.
    #[test]
    fn raw_string_fence_widens_past_collisions() {
        assert_eq!(rust_raw_string_literal("plain"), "r#\"plain\"#");
        // A bare `#` is harmless; only `"#` closes the fence.
        assert_eq!(rust_raw_string_literal("line \"#\""), "r##\"line \"#\"\"##");
        // Two hashes in the content force a three-hash fence.
        assert_eq!(rust_raw_string_literal("a\"##b"), "r###\"a\"##b\"###");
    }

    /// Every fence produced must actually survive a round trip: the content sits
    /// between `r<fence>"` and `"<fence>`, and that closing sequence must not
    /// appear inside it.
    #[test]
    fn raw_string_fence_is_unambiguous() {
        for src in [
            "simple",
            "with \"quotes\"",
            "write `#!/bin/sh`",
            "line \"#\"",
            "a\"#b\"##c\"###d",
            "trailing quote\"",
        ] {
            let lit = rust_raw_string_literal(src);
            // Layout is  r <hashes> " <content> " <hashes>
            let hashes = lit[1..].chars().take_while(|c| *c == '#').count();
            let fence = "#".repeat(hashes);
            let closing = format!("\"{fence}");
            let inner = &lit[hashes + 2..lit.len() - hashes - 1];
            assert_eq!(inner, src, "content round-trips for {src:?}");
            assert!(!src.contains(&closing), "fence {fence:?} collides in {src:?}");
        }
    }

    #[test]
    fn string_literal_escapes() {
        assert_eq!(rust_string_literal("a\"b\\c\nd"), "\"a\\\"b\\\\c\\nd\"");
    }

    /// A generated Cargo.toml must survive a Windows path without the backslashes
    /// being read as TOML escapes.
    #[test]
    fn toml_string_escapes_backslashes() {
        assert_eq!(toml_string(r"C:\repo\rust"), "\"C:\\\\repo\\\\rust\"");
    }
}
